### ISSUE TITLE
Missing parameters code and state. There might be an issue with your account. Try loggin out and registrer for a new account.

### ISSUE THREAD

**Issue by PrestaEdit** [prestascan/prestascansecurity#21]

**Comment by maxime-profileo** [comment]
Do you have this error during the registration?
I would recommend following these steps:
[> I was able to register but cannot finish the setup or cannot start a scan due to token or connectivity error, what can I do?](https://security.profileo.com/advisories/prestascansecurity/#:~:text=I%20was%20able%20to%20register%20but%20cannot%20finish%20the%20setup%20or%20cannot%20start%20a%20scan%20due%20to%20token%20or%20connectivity%20error%2C%20what%20can%20I%20do%3F)

**Comment by PrestaEdit** [comment]
When I try to add my account and on the email confirmation.

Deleting the account and redo make the same things.

**Comment by maxime-profileo** [comment]
Did you follow this step ?
>  reset the module (or uninstall it and install it again)

Because the error that you have typically means that your module has saved previous keys that are not matching the new token. Make also sure that you are always using the latest version.

**Comment by maxime-profileo** [comment]
Hello, without other reports of this issue or additional informations, we are closing this issue. Do not hesitate to re-open it if required.
